const config = {
    // Flight Logic
    completionThreshold: 98, // Percentage required to mark flight as "Success"

    // Data Source
    kmlFilePath: './lines.kml',
    // Folder of bundled sample KML files, selectable from the hamburger menu.
    // Must contain a manifest.json (auto-generated by the Vite kml-manifest plugin) listing the filenames.
    bundledKmlDir: './kml/',
    // Geoid undulation in meters for this area (geoid height above ellipsoid).
    // KML altitudes are treated as MSL; add this to get MSL.
    // e.g. undulation=40 means ellipsoidal 200m -> MSL 160m.
    geoidUndulation: 43.1,

    // UI / UX
    summaryAutoCloseSeconds: 10,
    notificationDurationSeconds: 3,
    summaryDialogTimeoutMs: 10000, // Derived, or just use seconds * 1000

    // Simulation Settings
    simulation: {
        speedKnots: 10,
        preStartDistanceFactor: 0.1, // Start 5% before the actual start point
        jitter: {
            horizontalMeters: 10, // Max +/- deviation in meters
            alt: 40,               // +/- 20m
            heading: 20            // +/- 10 degrees
        }
    },

    // Crosshair displacement limits (meters at which crosshair reaches max screen offset)
    crosshair: {
        maxCrossTrack: 500, // horizontal: +/- this many meters -> +/- 2*compassRadius px
        maxAltDiff: 200,    // vertical:   +/- this many meters -> +/- 2*compassRadius px
    },

    // Length of each colored chunk (meters) when rendering the flown track's quality on the map
    qualitySegmentLength: 10,

    // Limits for Halo Colors (meters)
    limits: {
        green: 2,   // Within this cross-track error -> Green Halo & Completes Line
        yellow: 4,  // Within this -> Yellow Halo. Above -> Red.
        vertical_green: 2, // Within this altitude error -> Green
        vertical_yellow: 4, // Within this -> Yellow. Above -> Red.
        heading_green: 5,  // Within this heading error (degrees) -> auto-start recording
        start_radius: 10   // Must be within this distance (meters) of start or end point to auto-start recording
    },

    // Dubins path planning mode (big map guidance to the flight line start)
    dubins: {
        minRadius: 300,           // meters, minimum turn radius for the planned path
        approachDistance: 500,    // meters before the line start where heading must already be aligned
        updateIntervalSeconds: 5  // minimum seconds between path recomputes
    }
};

export default config;
