const config = {
    // Flight Logic
    completionThreshold: 90, // Percentage required to mark flight as "Success"

    // Data Source
    kmlFilePath: './lines.kml',
    // Folder of bundled sample KML/TXT files, selectable from the hamburger menu.
    // Must contain a manifest.json (auto-generated by the Vite kml-manifest plugin) listing the filenames.
    bundledKmlDir: './kml/',
    // Offline OSM basemap: a zip containing a MapLibre style, PMTiles vector tile archive,
    // sprites and fonts, downloaded once and unpacked into the Origin Private File System (OPFS)
    // so the basemap renders fully offline afterwards (see src/utils/OsmAssets.js).
    // Relative to the deployed app root (same-origin, avoids CORS): served from public/osm/osm.zip
    // in dev, and from dist/osm/osm.zip (built from the same file) in production.
    osmPackageUrl: './osm/osm.zip',
    // Bump when osm.zip changes so devices re-download it instead of keeping the stale OPFS copy.
    osmPackageVersion: 2,
    osmPmtilesFileName: 'hungary-260719.osm.pmtiles',
    osmStyleFileName: 'style.json',
    // Geoid undulation in meters for this area (geoid height above ellipsoid).
    // KML altitudes are treated as MSL; add this to get MSL.
    // e.g. undulation=40 means ellipsoidal 200m -> MSL 160m.
    geoidUndulation: 43.1,

    // UI / UX
    summaryAutoCloseSeconds: 10,
    notificationDurationSeconds: 3,

    // Simulation Settings
    simulation: {
        speedKnots: 70,
        preStartDistanceFactor: 0.1, // Start this fraction of the line length before the start point, and continue the same distance past the end point
        jitter: {
            horizontalMeters: 10, // Max +/- deviation in meters
            alt: 40,               // +/- 20m
            heading: 20            // +/- 10 degrees
        }
    },

    // Crosshair displacement limits (meters at which crosshair reaches max screen offset)
    crosshair: {
        maxCrossTrack: 500, // horizontal: +/- this many meters -> +/- 2*compassRadius px
        maxAltDiff: 200,    // vertical:   +/- this many meters -> +/- 2*compassRadius px
    },

    // Length of each colored chunk (meters) when rendering the flown track's quality on the map
    qualitySegmentLength: 10,

    // Limits for Halo Colors (meters)
    limits: {
        green: 5,   // Within this cross-track error -> Green Halo & Completes Line
        yellow: 10,  // Within this -> Yellow Halo. Above -> Red.
        vertical_green: 5, // Within this altitude error -> Green
        vertical_yellow: 10, // Within this -> Yellow. Above -> Red.
        heading_green: 10,  // Within this heading error (degrees) -> auto-start recording
        heading_yellow: 15, // Within this heading error (degrees) -> Yellow. Above -> Red.
        start_radius: 15,  // Must be within this distance (meters) of start or end point to auto-start recording
        speed_green: 75,   // Below this speed (knots) -> Green Speed. Above -> Yellow/Red.
        speed_yellow: 80  // Below this speed (knots) -> Yellow Speed. Above -> Red.
    },

    // Dubins path planning mode (big map guidance to the flight line start)
    dubins: {
        minRadius: 300,           // meters, minimum turn radius for the planned path
        approachDistance: 500,    // meters before the line start where heading must already be aligned
        updateIntervalSeconds: 5  // minimum seconds between path recomputes
    }
};

export default config;
